(cl:in-package multiple_turtlebots_estm-msg)
(cl:export '(HEADER-VAL
          HEADER
          ODOM_X-VAL
          ODOM_X
          ODOM_Y-VAL
          ODOM_Y
          ODOM_THETA-VAL
          ODOM_THETA
          MEAS_RHO-VAL
          MEAS_RHO
          MEAS_BETA-VAL
          MEAS_BETA
          MEAS_THETA-VAL
          MEAS_THETA
          DELTA_T-VAL
          DELTA_T
          GT_RHO-VAL
          GT_RHO
          GT_BETA-VAL
          GT_BETA
          GT_THETA-VAL
          GT_THETA
          CASE0_X-VAL
          CASE0_X
          CASE0_Y-VAL
          CASE0_Y
          CASE0_T-VAL
          CASE0_T
          CASE1_X-VAL
          CASE1_X
          CASE1_Y-VAL
          CASE1_Y
          CASE1_T-VAL
          CASE1_T
          CASE2_X-VAL
          CASE2_X
          CASE2_Y-VAL
          CASE2_Y
          CASE2_T-VAL
          CASE2_T
          CASE3_X-VAL
          CASE3_X
          CASE3_Y-VAL
          CASE3_Y
          CASE3_T-VAL
          CASE3_T
          CASE4_X-VAL
          CASE4_X
          CASE4_Y-VAL
          CASE4_Y
          CASE4_T-VAL
          CASE4_T
          CASE4_VJ-VAL
          CASE4_VJ
          CASE4_WJ-VAL
          CASE4_WJ
))